# Generated by Django 5.0 on 2025-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmedia',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
