# Generated by Django 5.2.5 on 2025-09-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmedia",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="productmedia",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="productmedia",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="productmedia",
            name="video",
        ),
        migrations.AddField(
            model_name="productmedia",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[("image", "Image"), ("video", "Video")],
                max_length=10,
                null=True,
            ),
        ),
    ]
