# Generated by Django 5.2.5 on 2025-09-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_productmedia_image1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="products/"),
        ),
    ]
