# Generated by Django 5.0 on 2025-09-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
