# Generated by Django 5.0 on 2025-09-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='smallText',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
